/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/shoe-draco.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shoe-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.shoe.geometry} material={materials.mesh} />
      <mesh geometry={nodes.shoe_1.geometry} material={materials.caps} />
      <mesh geometry={nodes.shoe_2.geometry} material={materials.laces} />
    </group>
  )
}

useGLTF.preload('/shoe-draco-transformed.glb')
